spring.application.name=ecommerce-backend


spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=11445

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# JWT Configuration
jwt.secret=9a4f2c3e5b6a7e8d9c0b1a2f3e4d5c6b7a8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a
jwt.expiration-ms=86400000